CREATE TABLE nfl (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    GameId INTEGER NOT NULL,
    GameDate VARCHAR(100) NOT NULL,
    Quarter INTEGER NOT NULL,
    Minute INTEGER NOT NULL,
    Second INTEGER NOT NULL,
    OffenseTeam VARCHAR(100) NOT NULL,
    DefenseTeam VARCHAR(100) NOT NULL,
    Down INTEGER NOT NULL,
    ToGo INTEGER NOT NULL,
    YardLine INTEGER NOT NULL,
    SeriesFirstDown INTEGER NOT NULL,
    NextScore INTEGER NOT NULL,
    Description VARCHAR(100),
    TeamWin INTEGER NOT NULL,
    SeasonYear INTEGER NOT NULL,
    Yards INTEGER NOT NULL,
    Formation VARCHAR(100),
    PlayType VARCHAR(100),
    IsRush INTEGER,
    IsPass INTEGER,
    IsIncomplete INTEGER,
    IsTouchdown INTEGER,
    PassType VARCHAR(100),
    IsSack INTEGER,
    IsChallenge INTEGER,
    IsChallengeReversed INTEGER,
    IsMeasurement INTEGER,
    IsInterception INTEGER,
    IsFumble INTEGER,
    IsPenalty INTEGER,
    IsTwoPointConversion INTEGER,
    IsTwoPointConversionSuccessful INTEGER,
    RushDirection VARCHAR(100),
    YardLineFixed INTEGER,
    YardLineDirection VARCHAR(100),
    IsPenaltyAccepted INTEGER,
    PenaltyTeam VARCHAR(100),
    IsNoPlay INTEGER,
    PenaltyType VARCHAR(100),
    PenaltyYards INTEGER
);


CREATE TABLE scores (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    Score VARCHAR(100) NOT NULL,
    PtsW INTEGER NOT NULL,
    PtsL INTEGER NOT NULL,
    PtTot INTEGER NOT NULL,
    PtDif INTEGER NOT NULL,
    Winner VARCHAR(100) NOT NULL,
    Loser VARCHAR(100) NOT NULL,
    Date VARCHAR(100) NOT NULL
);